spring:
  datasource:
    master:
      url: jdbc:mysql://127.0.0.1:3309/test?characterEncoding=UTF-8&useSSL=false
      username: root
      password: root!@#
    slave:
      name: slave1,slave2
      slave1:
        url: jdbc:mysql://127.0.0.1:3308/test?characterEncoding=UTF-8&useSSL=false
        username: root
        password: root!@#
      slave2:
        url: jdbc:mysql://127.0.0.1:3310/test?characterEncoding=UTF-8&useSSL=false
        username: root
        password: root!@#