spring:
  kafka:
    bootstrap-servers: localhost:9001,localhost:9002,localhost:9003
    consumer:
      group-id: test1
      fetch-min-size: 1
      max-poll-records: 1
      properties:
        partition.assignment.strategy: org.apache.kafka.clients.consumer.RangeAssignor